# Generated by Django 4.1.7 on 2023-03-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sol',
            fields=[
                ('estado', models.BooleanField(auto_created=True, default=False)),
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('id_solicitante', models.IntegerField()),
                ('id_destinatario', models.IntegerField()),
            ],
            options={
                'db_table': 'solicitudes',
            },
        ),
    ]
