# Generated by Django 4.1.7 on 2023-04-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0004_alter_sol_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sol',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pending'), ('ACEPTADA', 'Accepted'), ('RECHAZADA', 'Rejected')], default='PENDING', max_length=9),
        ),
    ]
