# Generated by Django 4.1.7 on 2023-04-05 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solicitudes', '0005_alter_sol_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sol',
            name='usr_envia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_env', to=settings.AUTH_USER_MODEL, verbose_name='user_envia'),
        ),
        migrations.AlterField(
            model_name='sol',
            name='usr_recibe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rec', to=settings.AUTH_USER_MODEL, verbose_name='user_recibe'),
        ),
    ]
