# Generated by Django 4.1.7 on 2023-04-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0007_rename_sol_solicitudes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pending'), ('ACEPTADA', 'Accepted'), ('RECHAZADA', 'Rejected')], default='PENDIENTE', max_length=9),
        ),
    ]
