# Generated by Django 4.1.7 on 2023-04-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionLibros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
