# Generated by Django 4.1.7 on 2023-04-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionLibros', '0002_libros_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='sinopsis',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
