# Generated by Django 4.1.7 on 2023-04-03 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionLibros', '0003_libros_sinopsis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libros',
            old_name='nombre',
            new_name='titulo',
        ),
    ]
