# Generated by Django 4.1.7 on 2023-04-04 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestionLibros', '0004_rename_nombre_libros_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionLibros.libros', verbose_name='isbn')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='username')),
            ],
        ),
    ]
