# Generated by Django 4.1.7 on 2023-04-04 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionLibros', '0005_listas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listas',
            options={'verbose_name': 'Listas'},
        ),
    ]
