# Generated by Django 4.1.7 on 2023-04-04 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionLibros', '0006_alter_listas_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listas',
            options={},
        ),
        migrations.AlterModelTable(
            name='listas',
            table='listas',
        ),
    ]
