# Generated by Django 4.1.7 on 2023-04-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionLibros', '0007_alter_listas_options_alter_listas_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='listas',
            name='estado',
            field=models.CharField(default='', max_length=9),
        ),
    ]
