# Generated by Django 4.1.7 on 2023-04-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionLibros', '0009_alter_listas_isbn_alter_listas_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listas',
            name='estado',
            field=models.CharField(default='pendiente', max_length=9),
        ),
    ]
