# Generated by Django 4.1.7 on 2023-04-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionLibros', '0012_opiniones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='sinopsis',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
