# Generated by Django 4.1.7 on 2023-04-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otra_cosa',
        ),
        migrations.AddField(
            model_name='user',
            name='biografia',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterModelTable(
            name='user',
            table='login_usr',
        ),
    ]
