# Generated by Django 4.1.7 on 2023-04-04 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_user_options_remove_user_alias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fecha_nac',
            field=models.DateField(default=datetime.datetime(1, 1, 1, 0, 0)),
        ),
    ]
