# Generated by Django 4.1.7 on 2023-04-04 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_user_id_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='login_user',
        ),
    ]
