# Generated by Django 4.1.7 on 2023-04-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_remove_user_dni_remove_user_fecha_nac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='biografia',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
